language: node_js
node_js:
  - "6"
sudo: false
addons:
    chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script: 
  - npm test
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
